# Setup
title: ALICE HONG
description: full stack programmer
url: https://vszhub.github.io
locale: 'ko-KR'
name: 'alicehong1819'
avatar: /me.jpg
paginate: 5
permalink: pretty
cover_image: /

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - not-pure-poole
  - jekyll-remote-theme

remote_theme: vszhub/not-pure-poole


# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - scripts/
  - not-pure-poole.gemspec

# Optimize Jekyl SEO Tag
twitter:
  username: alicehong1819
  card: summary
logo: logo.png
social:
  name: Alice Hong
  links:
    - https://twitter.com/alicehong1819
    - https://github.com/jeoungwonhong
google_site_verification: xxxxx
lang: ko

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
# google_analytics: UA-000000-0

# Replace this value and uncomment to enable Disqus
# disqus: xxxxxx

# Specify the author for blog posts
author:
  name: jeoungwonhong
  url: https://github.com/jeoungwon
  email: alicehong1819@naver.com
